### PR TITLE
Add notes about units in ncdc responses

### PR DESCRIPTION
**Pull request by amoeba**
Addresses #265

As per #265, I added some notes in relevant places warning users about odd units.

## Description

Adds notes in:

- README
- `ncdc` vignette
- `ncdc` docs

## Related Issue

#265 

## Notes

I couldn't get the README to knit or the vignettes to build (or tests to run), so I haven't done that here.

### CODE REVIEW

**Comment by sckott** [comment]
thanks, no worries about tests/etc. that's something I need to improve so its easier for folks. 

Looks good to me!

**Comment by sckott** [comment]
actually, i forgot about something. since you opened that issue, I did https://github.com/ropensci/rnoaa/pull/289 - so `ncdc()` now has a parameter `add_units` where you can add units to the output data.frame (the default is `FALSE`, so does not add them). e.g., 

```r
ncdc(datasetid='GHCND', stationid='GHCND:USW00014895', startdate = '2013-10-01', enddate = '2013-12-01', add_units=TRUE)$data
#> # A tibble: 25 x 9
#>    date                datatype station           value fl_m  fl_q  fl_so fl_t  units
#>    <chr>               <chr>    <chr>             <int> <chr> <chr> <chr> <chr> <chr>
#>  1 2013-10-01T00:00:00 AWND     GHCND:USW00014895    29 ""    ""    W     ""    meters_per_sec_tenths
#>  2 2013-10-01T00:00:00 PRCP     GHCND:USW00014895     0 ""    ""    W     2400  mm_tenths
#>  3 2013-10-01T00:00:00 SNOW     GHCND:USW00014895     0 ""    ""    W     ""    mm
#>  4 2013-10-01T00:00:00 SNWD     GHCND:USW00014895     0 ""    ""    W     ""    mm
#>  5 2013-10-01T00:00:00 TAVG     GHCND:USW00014895   179 H     ""    S     ""    celcius_tenths
#>  6 2013-10-01T00:00:00 TMAX     GHCND:USW00014895   250 ""    ""    W     2400  celcius_tenths
#>  7 2013-10-01T00:00:00 TMIN     GHCND:USW00014895   133 ""    ""    W     2400  celcius_tenths
#>  8 2013-10-01T00:00:00 WDF2     GHCND:USW00014895   210 ""    ""    W     ""    degrees
#>  9 2013-10-01T00:00:00 WDF5     GHCND:USW00014895   230 ""    ""    W     ""    degrees
#> 10 2013-10-01T00:00:00 WSF2     GHCND:USW00014895    76 ""    ""    W     ""    meters_per_sec_tenths
#> # … with 15 more rows
#> 
#> attr(,"class")
#> [1] "ncdc_data"
```

if `add_units=TRUE` - we use manually curated metadata files in the R folder that start with `units-`, e.g, https://github.com/ropensci/rnoaa/blob/master/R/units-normal_ann.R to populate a units field in the output data.frame. 

There's some NOAA datasets that have missing data in these files - it's a huge PITA figuring out all the units for all the different variables -

Anyway, can you add something to the docs about this feature?

**Comment by amoeba** [comment]
Whoa, that's really great. Will do.

**Comment by amoeba** [comment]
Added in c94358b971c5a3845ace935b85cd4fc48f117433. Have a look! Thanks for catching this.

**Comment by sckott** [comment]
this is great, thanks a lot @amoeba

**Pull request merged**
