### PR TITLE
updates ropenaq vignette

### PR DESCRIPTION
**Pull request by maelle**
I updated the `ropenaq` code in the vignette because it can now be simpler.

I've noticed an issue with the unit in the tables. I'm unsure about what caused this encoding problem, and my first name seems to be ok. Any idea?

### CODE REVIEW

**Comment by sckott** [comment]
thanks @maelle ! looks good. I'll try to fix encoding after merging. is that okay?

**Comment by maelle** [comment]
Of course, thank you!

**Comment by sckott** [comment]
reran the vignette on my machine, https://github.com/ropensci/rnoaa/blob/master/vignettes/rnoaa_ropenaq.Rmd looks okay i think, although the first table is a bit wide, and at least in Rstudio, looks awkward, maybe dates can be shortened

**Comment by maelle** [comment]
Thanks a lot! It's wide but ok thanks to scrolling ?

**Pull request merged**
