### PR TITLE
Add stop if windows until ncdf4 and grib2 issues in bug #127 are resolved.

### PR DESCRIPTION
**Pull request by potterzot**

### CODE REVIEW

**Comment by sckott** [comment]
Sorry - `is_windows()` is not a fxn in base R - you can tell from the snake case :) 

here's the little function I made 

```r
is_windows <- function() {
    .Platform$OS.type == "windows"
}
```

can you add that

**Comment by potterzot** [comment]
Sure, though maybe it makes more sense for is_windows() to be in zzz.R?

---------------------
Nicholas Potter
http://potterzot.com

**Comment by sckott** [comment]
yeah

**Comment by sckott** [comment]
thanks!

**Pull request merged**
