### PR TITLE
Vectorises ghcn

### PR DESCRIPTION
**Pull request by eliocamp**
I thought it would be useful if the function `ghcn()` could accept a vector of station ids.

### CODE REVIEW

**Comment by sckott** [comment]
perhaps. `ghcnd()` is used within `ghcnd_search()`, which is used within `meteo_tidy_ghcnd()`. So this change will have to be checked carefully that it doesn't break those other 2 functions

**Comment by eliocamp** [comment]
`ghcnd_search()` works with length one arguments and vector arguments (i.e. it inherits vectorisation for free :money_mouth_face: )

`meteo_tidy_ghncd()` works for length one argumenta but fails for vector arguments with error: `Each row of output must be identified by a unique combination of keys`. 

I can modify `meteo_tidy_ghncd()` so that it's also vectorised.

**Comment by eliocamp** [comment]
Ouch, sorry! It totally fell off my plate. I'll get to it this weekend. Apologies!

**Comment by eliocamp** [comment]
There! 
The relevant tests run well on my machine. I tried to test the whole package to see if I accidentally broke something else (not likely, since the changes are well contained to one function) but I got too many failures related to missing API keys.

**Comment by sckott** [comment]
Thanks @eliocamp !  Can you send a new pull request on a branch with a different name? There's so many files changed in this PR it makes it hard to know what's going on

**Pull request closed without merging**
